# Generated by Django 5.1.4 on 2024-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('circuit', models.CharField(help_text='EVOK API circuit ID', max_length=50)),
                ('state', models.BooleanField(default=False, help_text='Current state of the input')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('circuit', models.CharField(help_text='EVOK API circuit ID', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Current state of the relay')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
