# Generated by Django 5.1.4 on 2024-12-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_digitalinput_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max_temp',
            field=models.FloatField(default=100.0, help_text='Maximum acceptable temperature'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_temp',
            field=models.FloatField(default=0.0, help_text='Minimum acceptable temperature'),
        ),
    ]
