# Generated by Django 5.1.4 on 2024-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sensor_max_temp_sensor_min_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(default='Log message missing'),
            preserve_default=False,
        ),
    ]
