# Generated by Django 5.1.4 on 2024-12-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tank',
            field=models.ForeignKey(blank=True, help_text='Related tank for this log, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tank'),
        ),
    ]
