# Generated by Django 5.1.4 on 2024-12-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_log_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='max_temp',
            field=models.FloatField(default=25.0, help_text='Maximum acceptable temperature'),
        ),
    ]
