# Generated by Django 5.1.4 on 2024-12-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sensor_max_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
