# Generated by Django 5.1.4 on 2024-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_log_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='error_active',
            field=models.BooleanField(default=False, help_text='Indicates if the sensor is currently in error state.'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_error_time',
            field=models.DateTimeField(blank=True, help_text='Time of the last detected error.', null=True),
        ),
    ]
