# Generated by Django 5.1.4 on 2025-01-04 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sensor_error_active_sensor_last_error_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='circuit',
            field=models.CharField(help_text='xG18 Modbus circuit ID (e.g., xG18_1, xG18_2)', max_length=50, validators=[django.core.validators.RegexValidator('^xG18_\\d$', message="Circuit must match format 'xG18_<digit>'")]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='The temperature sensor associated with this tank.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sensor'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='target_temperature',
            field=models.FloatField(default=20.0, help_text='Desired temperature for the tank.'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='valve',
            field=models.ForeignKey(blank=True, help_text='The valve associated with this tank.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.valve'),
        ),
    ]
