# Generated by Django 5.1.4 on 2025-01-04 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tank_created_at_remove_tank_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Related sensor for this log, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sensor'),
        ),
    ]
